### ISSUE TITLE
Artsnob

### ISSUE THREAD

**Issue by luismachita** [luismachita/artsnob#1]
Project done.

**Comment by Joe21** [comment]
• Awesome visual functionality on front end, love the sign up process. Slick!
• Might want to add a mouse on hover cursor to hand image for the sign up button, just to add a bit more ux.
• The overall complexity of functionality is very impressive. The code remains rather succinct despite lots of various things occurring. Nicely done!
• This app might be an example of something that might not necessarily be suited for single page application, or perhaps, if given more time, rerendering of the DOM so that multiple bits of functionality aren't all displayed at once. That's purely imho though as I am not a ux/di expert, but there's a lot going on.
• One minor bug with the sketching long/latitude being off from my mouse cursor. Really really cool addition!
•  Overall, very impressive project. You did a great job tying in everything from the program and really showed a strong grasp of complex, various functionality in a rather short period.

- Joe Jung
